# SPDX-License-Identifier: Apache-2.0
"""Diagnostic-only fixed recipe submission, without a serving-model wrapper.

Retains the exact recipes generated by hpu_backend. This uses the maintained
PreparedGroupPlan compute submission API; it does not claim joint HCL replay.
"""
from pathlib import Path
import os
import ctypes
import json
import hashlib
import importlib.util

import torch
from torch import nn


class RecipeRecorder:

    def __init__(self, evidence, *, backend=None):
        from habana_frameworks.torch.dynamo.compile_backend.passes import (OptimizationPassPlacement,
                                                                           register_pass_at_optimization_pass)
        from vllm_gaudi.distributed.tp2_fused_ar_norm import _load_bridge, _verify_prepared_runtime
        import habana_frameworks.torch.distributed.hccl  # noqa: F401
        self.calls = None
        path = Path(os.environ["VLLM_HPU_TP2_FUSED_AR_NORM_BRIDGE"])
        self.bridge = _load_bridge(path)
        if not torch.distributed.is_initialized():
            torch.distributed.init_process_group("hccl",
                                                 init_method=f"file://{evidence / 'micro-rendezvous'}",
                                                 rank=0,
                                                 world_size=1)
        _verify_prepared_runtime(path)
        # Production imports expose the runtime globally. The standalone HCCL
        # communicator can leave it RTLD_LOCAL; promote the already verified
        # loaded object, never load a second Synapse implementation.
        loaded = {
            Path(row.rsplit(maxsplit=1)[-1]).resolve()
            for row in Path("/proc/self/maps").read_text().splitlines()
            if row.rsplit(maxsplit=1)[-1].endswith("/libSynapse.so")
        }
        if len(loaded) != 1:
            raise RuntimeError("Expected exactly one already loaded Synapse")
        synapse = loaded.pop()
        ctypes.CDLL(str(synapse), mode=os.RTLD_NOW | os.RTLD_NOLOAD | os.RTLD_GLOBAL)
        (evidence / "native-compute-runtime.json").write_text(
            json.dumps(
                {
                    "loaded_synapse": str(synapse),
                    "sha256": hashlib.sha256(synapse.read_bytes()).hexdigest(),
                    "bridge_abi_manifest": str(path.with_suffix(".abi.json"))
                },
                indent=2))
        self.backend = (backend if backend is not None else
                        torch.distributed.distributed_c10d._get_default_group()._get_backend(torch.device("hpu")))
        library = Path(os.environ["DSV41_MICRO_COMPUTE_LIBRARY"])
        if hashlib.sha256(library.read_bytes()).hexdigest() != os.environ["DSV41_MICRO_COMPUTE_SHA256"]:
            raise RuntimeError("Native micro diagnostic binary fingerprint differs")
        spec = importlib.util.spec_from_file_location("dsv41_micro_compute", library)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        self.module = module
        self.Compute = module.Compute

        owner = self

        class Observe(nn.Module):

            def __init__(self, recipe):
                super().__init__()
                self.recipe = recipe

            def forward(self, *inputs):
                result = self.recipe(*inputs)
                if owner.calls is not None:
                    outputs = list(result) if isinstance(result, (tuple, list)) else [result]
                    duplicates = set((self.recipe._in_to_out_dups or {}).values())
                    allocated = [t for i, t in enumerate(outputs) if i not in duplicates]
                    owner.calls.append((self.recipe._recipe_id, list(inputs), allocated))
                return result

        def observe(context):
            changed = False
            for name, child in list(context.graph_module.named_children()):
                if hasattr(child, "_recipe_id"):
                    context.graph_module.add_module(name, Observe(child))
                    changed = True
            return changed

        register_pass_at_optimization_pass(observe, OptimizationPassPlacement.POST_PARTITIONER)

    def prepare(self, fn, inputs, weights):
        self.calls = []
        results = [fn(x, *w) for x, w in zip(inputs, weights, strict=True)]
        torch.hpu.synchronize()
        calls, self.calls = self.calls, None
        if not calls:
            raise RuntimeError("No compiled recipes observed; micro replay must not silently use Python dispatch")
        plan = self.bridge.PreparedGroupPlan()
        slots, external, tensors = {}, [], {}

        def key(value):
            if isinstance(value, torch.Tensor):
                return ("tensor", value.data_ptr(), tuple(value.shape), value.stride(), value.dtype)
            return (type(value), value)

        def slot(value, is_input):
            identity = key(value)
            if identity not in slots:
                if isinstance(value, torch.Tensor) and value.is_contiguous():
                    for known, tensor in tensors.items():
                        if (tensor.data_ptr() == value.data_ptr() and tensor.dtype == value.dtype
                                and tensor.numel() == value.numel() and tensor.is_contiguous()):
                            slots[identity] = plan.add_reshape_view(slots[known], list(value.shape))
                            return slots[identity]
                slots[identity] = plan.add_slot(value, is_input)
                if isinstance(value, torch.Tensor):
                    tensors[identity] = value
                if is_input:
                    external.append(value)
            return slots[identity]

        for recipe, arguments, outputs in calls:
            source = [slot(t, True) for t in arguments]
            destination = [slot(t, False) for t in outputs]
            plan.add_compute(recipe, source, destination)
        visible = [t for row in results for t in (row if isinstance(row, (tuple, list)) else (row, ))]
        for tensor in visible:
            assert any(value.data_ptr() == tensor.data_ptr() and value.numel() == tensor.numel()
                       for value in tensors.values()), "Unobserved output allocation"
        output_slots = [slot(t, False) for t in visible]
        plan.prepare(self.backend, output_slots)
        native = self.Compute()
        native.begin()
        self.bridge.replay_prepared_groups([plan], [external])
        native.end(len(calls))
        torch.hpu.synchronize()
        return PreparedReplay(self.bridge, plan, external, visible, len(calls), native)


class PreparedReplay:

    def __init__(self, bridge, plan, inputs, outputs, recipes, native):
        self.bridge, self.plan = bridge, plan
        self.inputs, self.outputs, self.recipes = inputs, outputs, recipes
        self.native = native

    def __call__(self):
        self.native.replay()

    def close(self):
        self.native.close()
        self.plan.invalidate()
