# SPDX-License-Identifier: Apache-2.0
"""Freeze N256 weights/scales into four bounded-memory TP2 x PP2 files."""
import argparse
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
import math
from pathlib import Path
import shutil

from vllm_gaudi.ops.deepseek_v41_expert_n256 import FINGERPRINT, LAYOUT, prepare_expert, restore_expert
from vllm_gaudi.ops.deepseek_v41_fp8 import FINGERPRINT as QUANTIZATION_FINGERPRINT, read_expert
from vllm_gaudi.ops.deepseek_v41_n256_shards import runtime_specs
from vllm_gaudi.ops.deepseek_v41_shard_loader import PreparedV41Shard
from vllm_gaudi.ops.deepseek_v41_weights import RankWriter, file_hash, publish_json
import numpy as np


def prepare_rank(shard, directory):
    rank = f"pp{shard.pp_rank}-tp{shard.tp_rank}"
    specs = runtime_specs(shard)
    path = directory / f"{rank}.safetensors"
    partial = path.with_suffix(".partial")
    writer = RankWriter(partial, specs, {"layout_fingerprint": FINGERPRINT, "source_rank": rank})
    matrices, peak = 0, 0
    try:
        for name in sorted(specs):
            if not name.endswith("_q16"):
                continue
            prefix = name.removesuffix("_q16")
            q, s = (shard.catalog[prefix + suffix] for suffix in ("_q16", "_s16"))
            for expert in range(q.shape[0]):
                original_q, original_s = read_expert(q, expert), read_expert(s, expert)
                prepared_q, planes, channel, report = prepare_expert(original_q, original_s)
                # Audit exact nibble/scale preservation for the full export,
                # not only a random expert. Channel scales are generated by
                # the same function as the current on-load reference.
                restored_q, restored_s = restore_expert(prepared_q, planes)
                if not np.array_equal(original_q, restored_q) or not np.array_equal(original_s, restored_s):
                    raise RuntimeError(f"N256 inverse check failed: {rank}/{prefix}/{expert}")
                for suffix, data in (("_q16", prepared_q), ("_s16", planes), ("_fp8_channel", channel)):
                    writer.write(prefix + suffix, expert * data.nbytes, data)
                peak = max(peak, report["temporary_upper_bound_bytes"] + original_q.nbytes + original_s.nbytes)
                if peak > 2 * 2**30:
                    raise RuntimeError("N256 preparation exceeds the 2 GiB per-rank workspace")
                matrices += 1
            shard.check_identity()
            print(f"{rank}: {prefix}; {matrices} expert matrices ready", flush=True)
        writer.sync()
    finally:
        writer.close()
    partial.replace(path)
    digest = file_hash(path)
    stat = path.stat()
    record = {"file": path.name, "bytes": stat.st_size, "sha256": digest,
              "inode": stat.st_ino, "mtime_ns": stat.st_mtime_ns,
              "source_sha256": shard.manifest["rank_files"][rank]["sha256"],
              "verified_expert_matrices": matrices, "temporary_upper_bound_bytes": peak}
    publish_json(directory / f"{rank}-record.json", record)
    return rank, record


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("prepared", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--workers", type=int, default=4)
    args = parser.parse_args()
    if not 1 <= args.workers <= 4:
        parser.error("--workers must be between 1 and 4")
    shards = [PreparedV41Shard(args.prepared, pp, tp) for pp in range(2) for tp in range(2)]
    required = sum(math.prod(spec["shape"]) * 2 for shard in shards for spec in runtime_specs(shard).values())
    args.output.parent.mkdir(parents=True, exist_ok=True)
    if shutil.disk_usage(args.output.parent).free < required + (8 << 30):
        raise RuntimeError(f"N256 export requires {required} bytes plus 8 GiB free headroom")
    args.output.mkdir(exist_ok=False)
    manifest = {"schema_version": 1, "layout": LAYOUT, "layout_fingerprint": FINGERPRINT,
                "quantization_fingerprint": QUANTIZATION_FINGERPRINT,
                "source_manifest_sha256": file_hash(args.prepared / "manifest.json"),
                "tensor_parallel_size": 2, "pipeline_parallel_size": 2,
                "rank_files": {}, "scope": "runtime expert weights; dense/Engram use existing immutable sources"}
    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        jobs = [pool.submit(prepare_rank, shard, args.output) for shard in shards]
        for future in as_completed(jobs):
            rank, record = future.result()
            manifest["rank_files"][rank] = record
            publish_json(args.output / "progress.json", manifest)
    manifest["prepared_at"] = datetime.now(timezone.utc).isoformat()
    # The loader accepts only this final publication after all four files are
    # complete, reversible and hashed. Partial builds are never served.
    publish_json(args.output / "manifest.json", manifest)


if __name__ == "__main__":
    main()
